# Generated by Django 2.1.5 on 2019-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dateE',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timeE',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
